server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8

spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: starbucks
    password: starbucks1234
    url: jdbc:mysql://localhost:3306/starbucksdb
    
  jpa:
    hibernate:
      ddl-auto: create  #create update none
    show-sql: true
